-- Enable Row Level Security (RLS) on all tables to satisfy Supabase security linter
-- and prevent unauthorized access via the PostgREST API.
-- Because the Express backend connects using a superuser/service role,
-- it will bypass these RLS policies and continue to function normally.

ALTER TABLE IF EXISTS "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "subjects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "topic_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "pyq_tracking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "revisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "weak_topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "uploads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "study_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "focus_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "goals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "revision_schedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "achievements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_achievements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "streaks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "attachments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "flashcards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "analytics_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ai_insights" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "assistant_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "study_rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "study_room_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "study_room_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "password_reset_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "email_verification_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "oauth_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_mfa_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "study_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "study_group_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "discussion_threads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "discussion_comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "file_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "InterviewPrep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "PlacementTracker" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CommunityPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Leaderboard" ENABLE ROW LEVEL SECURITY;
